version: '3.7'

services:
  powersimdata:
    container_name: scenario_client
    hostname: scenario_client
    environment: 
      - BE_SERVER_USER=${BE_SERVER_USER}
      - BE_SERVER_ADDRESS=scenario_server
      - BE_SERVER_SSH_PORT=2222
    image: powersimdata:latest
    networks:
      - cemnet
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - cemdata:/mnt/bes/pcm
      - ~/.ssh:/root/.ssh
      - $PWD/client_files:/root/ScenarioData
      - $PWD/tests:/app/tests
  scenario_server:
    container_name: scenario_server
    hostname: scenario_server
    # image: linuxserver/openssh-server
    image: scenario_server:latest
    networks:
      - cemnet
    tty: true
    volumes:
      - ~/.ssh/id_ed25519.pub:/pub_key/id_ed25519.pub:ro # path to ssh public key
      - $PWD/server_files:/mnt/bes/pcm
    environment:
      - USER_NAME=${BE_SERVER_USER}
      - PUBLIC_KEY_FILE=/pub_key/id_ed25519.pub # ssh public key in container
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=false
    restart: "unless-stopped"
  # reisejl:
  #   image: reisejl:latest
  #   networks:
  #     - cemnet
  #   ports:
  #     - "80:5000"
  #   volumes:
  #     - cemdata:/mnt/bes/pcm
  db:
    container_name: scenario_db
    hostname: scenario_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - cemnet
    volumes:
        - $PWD/sql:/docker-entrypoint-initdb.d

  adminer:
    container_name: scenario_db_adminer
    hostname: scenario_db_adminer
    image: adminer
    networks:
      - cemnet
    restart: always
    ports:
      - 8080:8080
networks:
  cemnet:
volumes:
  cemdata:
