version: '3.7'

services:
  powersimdata:
    container_name: powersimdata
    build:
      context: ../../PowerSimData
    image: powersimdata:latest
    entrypoint: bash
  postreise:
    container_name: postreise
    hostname: postreise
    build:
      context: ../../PostREISE
    depends_on:
      - powersimdata
    environment:
      - BE_SERVER_USER=${BE_SERVER_USER}
      - DEPLOYMENT_MODE=1
    image: postreise:latest
    ports:
      - 10000:10000
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ../rootdir/:/mnt/bes/pcm:ro
